name: BuildSize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List files
        run: ls -la

      - name: Set bundle size
        run: |
          STR=$(du -sh .next)
          echo "$STR"
          SIZE=$("$STR" | grep -o -E "\d+M")
          echo "$SIZE"
          echo "::set-output name=size::$SIZE"
        id: bundle-size
        shell: bash

      - name: Echo bundle size
        run: echo "size is ${{ steps.bundle-size.outputs.size }}"
