name: BuildSize

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List files
        run: ls -la

      - name: Set bundle size
        run: |
          SIZE=$(du -sh .next | grep -o -E "[0-9]+M")
          echo "$SIZE"
          echo "::set-output name=size::$SIZE"
        id: bundle-size
        shell: bash

      - name: Echo bundle size
        run: echo "size is ${{ steps.bundle-size.outputs.size }}"
        
      - name: Make comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '${{ Generated bundle size is: steps.bundle-size.outputs.size }}'
          comment_includes: 'bundle'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
